# Azure Devops Pipeline definition
# 
# Will build and release packages on Gitflow branch triggers (main, release/*).
# In build phase it will apply semver versioning with help of GitVersion (plugin needed).
# The results of the build are stored in a package on Azure Devops.
# After the build phase the deployment phase follows. During this phase it will checkout the
# github repository containing a Kodi addon repository and add the new package so users can
# download it.
# There are 2 deployment phases, first one for staging where only beta/release candidates are 
# deployed. Second one is the main repository for official releases (based on master/main branch).
#
# Needed extensions:
# - GitTools / GitVersion
# - RegEx Match & Replace
#
# Needed variables (var groups in library)
# - repository.variables
#   - git_emailAddress 
#   - git_userName
#   - github_token
trigger:
- master-fork
- release/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  isMaster: or(${{eq(variables['Build.SourceBranch'], 'refs/heads/master-fork')}},${{eq(variables['Build.SourceBranch'], 'refs/heads/main')}})
  isReleaseCandidate: ${{startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')}}
  isHotfix: ${{startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')}}
  isDev: ${{eq(variables['Build.SourceBranch'], 'refs/heads/dev')}}
  workingDirectory: '$(Build.SourcesDirectory)'

stages:
- stage: Build
  displayName: Build stage
  jobs:
    - job: build
      displayName: build
        
      steps:
      - task: gitversion/setup@0
        displayName: 'Install GitTools'
        inputs:
          versionSpec: '5.3.x'

      - task: gitversion/execute@0
        displayName: 'Executing gitversion'

      - script: |
            echo '##vso[task.setvariable variable=packageVersion]$(GitVersion.LegacySemVer)
            echo '##vso[task.setvariable variable=projectVersion]$(GitVersion.Major).$(GitVersion.Minor).$(GitVersion.Patch)
        displayName: 'Setting version variables'
        condition: not(eq(${{variables.isMaster}}, true))
        
      - script: |
            echo '##vso[task.setvariable variable=packageVersion]$(GitVersion.Major).$(GitVersion.Minor).$(GitVersion.Patch)
            echo '##vso[task.setvariable variable=projectVersion]$(GitVersion.Major).$(GitVersion.Minor).$(GitVersion.Patch)
        displayName: 'Setting version variables'
        condition: eq(${{variables.isMaster}}, true)

      - task: RegExMatchReplace@2
        displayName: 'Set addon version'
        inputs:
          PathToFile: 'addon.xml'
          RegEx: 'version="\d+\.\d+\.\d+.*" provider'
          ValueToReplace: 'version="$(packageVersion)" provider'
    
      - task: PythonScript@0
        displayName: 'Add changelog in addon.xml'
        inputs:
          scriptSource: 'inline'
          arguments: '$(workingDirectory)/addon.xml $(workingDirectory)/changelog.txt'
          script: |
            import sys, os, re

            addon_file = sys.argv[1]
            changelog_file = sys.argv[2]
            addon_xml = '' 
            changelog_txt = ''
            
            with open(addon_file, 'r') as f:
              addon_xml = f.read()
            with open(changelog_file, 'r') as f:
              changelog_txt = f.read()

            addon_xml = re.sub('<news>(.*)</news>', changelog_txt, addon_xml)
            with open(addon_file, 'w') as f:
              f.write(addon_xml)
          workingDirectory: '$(workingDirectory)'
          
      - task: CopyFiles@2
        displayName: 'Copy addon files for package'
        inputs:
          SourceFolder: ''
          Contents: |
              *.py
              *.md
              *.xml
              *.txt
              resources/**/*.*
              media/**/*.*
          TargetFolder: '$(build.artifactstagingdirectory)/plugin.program.akl/'
          CleanTargetFolder: true
          flattenFolders: false
          OverWrite: true

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(build.artifactstagingdirectory)/plugin.program.akl'
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: '$(build.artifactstagingdirectory)/package/plugin.program.akl-$(packageVersion).zip'
          replaceExistingArchive: true
 
      - task: CopyFiles@2
        displayName: 'Copy addon files for repository'
        inputs:
          SourceFolder: '$(build.artifactstagingdirectory)/plugin.program.akl/'
          Contents: |
              addon.xml
              media/**/*.*
          TargetFolder: '$(build.artifactstagingdirectory)/package/'
          CleanTargetFolder: false
          flattenFolders: false
          OverWrite: true

      - script: md5sum plugin.program.akl-$(packageVersion).zip > plugin.program.akl-$(packageVersion).zip.md5
        workingDirectory: $(build.artifactstagingdirectory)/package/
        displayName: 'Creating md5 file for zipfile'

      - script: md5sum addon.xml > addon.xml.md5
        workingDirectory: $(build.artifactstagingdirectory)/package/
        displayName: 'Creating md5 file for addonxml'

      - task: PublishBuildArtifacts@1
        displayName: 'Publishing application as artifact'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)/package/'
          ArtifactName: 'plugin.program.akl'
          publishLocation: 'Container'
     
- stage: DeployStaging
  displayName: Deployment on Staging
  condition: and(succeeded(),or(eq(${{variables.isReleaseCandidate}}, true),eq(${{variables.isHotfix}}, true),eq(${{variables.isMaster}}, true)))
  jobs:
    - deployment: Staging
      environment: 
        name: Staging

      variables:
        - group: repository.variables

      strategy:     
        runOnce:
          deploy:
            steps:
            - download: current
              displayName: 'Downloading Application artifact'
              artifact: 'plugin.program.akl'

            - script: |
                git clone https://github.com/chrisism/repository.chrisism.dev.git
              workingDirectory: $(Pipeline.Workspace)/
              displayName: 'Clone git repository'

            - script: |
                git config user.email $(git_emailAddress)
                git config user.name $(git_userName)
              workingDirectory: $(Pipeline.Workspace)/repository.chrisism.dev/
              displayName: 'Configure git settings'

            - task: CopyFiles@2
              displayName: 'Copy addon into git repository'
              inputs:
                SourceFolder: '$(Pipeline.Workspace)/plugin.program.akl'
                Contents: '**/*.*'
                TargetFolder: '$(Pipeline.Workspace)/repository.chrisism.dev/plugin.program.akl'
                CleanTargetFolder: false
                flattenFolders: false
                OverWrite: true

            - task: PythonScript@0
              displayName: 'Merge addon xml files for repository'
              inputs:
                scriptSource: 'inline'
                arguments: '$(Pipeline.Workspace)/repository.chrisism.dev/addons.xml $(Pipeline.Workspace)/repository.chrisism.dev/plugin.program.akl/addon.xml'
                script: |
                  import sys
                  from xml.etree import ElementTree

                  file_combined = sys.argv[1]
                  file_source = sys.argv[2]

                  addons_xml    = ElementTree.parse(file_combined)
                  addons        = addons_xml.getroot()
                  addon_in      = ElementTree.parse(file_source).getroot()

                  nodes = addons.findall("addon[@id='plugin.program.akl']")

                  for addon_node in nodes:
                      addons.remove(addon_node)

                  addons.append(addon_in)
                  addons_xml.write(file_combined)
                workingDirectory: '$(Pipeline.Workspace)/repository.chrisism.dev/'
                
            - script: md5sum addons.xml > addons.xml.md5
              workingDirectory: $(Pipeline.Workspace)/repository.chrisism.dev/
              displayName: 'Creating md5 file for addons.xml'

            - script: |
                git add .
                git commit -m "$(Build.DefinitionName) Release $(Build.BuildNumber)"
              workingDirectory: $(Pipeline.Workspace)/repository.chrisism.dev/
              displayName: 'Git - Add and commit'    

            - script: |
                git push https://$(github_token)@github.com/chrisism/repository.chrisism.dev.git main 
              workingDirectory: $(Pipeline.Workspace)/repository.chrisism.dev/plugin.program.akl
              displayName: 'Git - Push'    

- stage: DeployProd
  displayName: Deployment on Production
  condition: and(succeeded(),eq(${{variables.isMaster}}, true))
  jobs:
    - deployment: Production
      environment: 
        name: Production

      variables:
        - group: repository.variables

      strategy:     
        runOnce:
          deploy:
            steps:
            - download: current
              displayName: 'Downloading Application artifact'
              artifact: 'plugin.program.akl'

            - script: |
                git clone https://github.com/chrisism/repository.chrisism.git
              workingDirectory: $(Pipeline.Workspace)/
              displayName: 'Clone git repository'

            - script: |
                git config user.email $(git_emailAddress)
                git config user.name $(git_userName)
              workingDirectory: $(Pipeline.Workspace)/repository.chrisism/
              displayName: 'Configure git settings'

            - task: CopyFiles@2
              displayName: 'Copy addon into git repository'
              inputs:
                SourceFolder: '$(Pipeline.Workspace)/plugin.program.akl'
                Contents: '**/*.*'
                TargetFolder: '$(Pipeline.Workspace)/repository.chrisism/plugin.program.akl'
                CleanTargetFolder: false
                flattenFolders: false
                OverWrite: true

            - task: PythonScript@0
              displayName: 'Merge addon xml files for repository'
              inputs:
                scriptSource: 'inline'
                arguments: '$(Pipeline.Workspace)/repository.chrisism/addons.xml $(Pipeline.Workspace)/repository.chrisism/plugin.program.akl/addon.xml'
                script: |
                  import sys
                  from xml.etree import ElementTree

                  file_combined = sys.argv[1]
                  file_source = sys.argv[2]

                  addons_xml    = ElementTree.parse(file_combined)
                  addons        = addons_xml.getroot()
                  addon_in      = ElementTree.parse(file_source).getroot()

                  nodes = addons.findall("addon[@id='plugin.program.akl']")

                  for addon_node in nodes:
                      addons.remove(addon_node)

                  addons.append(addon_in)
                  addons_xml.write(file_combined)
                workingDirectory: '$(Pipeline.Workspace)/repository.chrisism/'
                
            - script: md5sum addons.xml > addons.xml.md5
              workingDirectory: $(Pipeline.Workspace)/repository.chrisism/
              displayName: 'Creating md5 file for addons.xml'

            - script: |
                git add .
                git commit -m "$(Build.DefinitionName) Release $(Build.BuildNumber)"
              workingDirectory: $(Pipeline.Workspace)/repository.chrisism/
              displayName: 'Git - Add and commit'    

            - script: |
                git push https://$(github_token)@github.com/chrisism/repository.chrisism.git master 
              workingDirectory: $(Pipeline.Workspace)/repository.chrisism/plugin.program.akl
              displayName: 'Git - Push'    
